### ISSUE TITLE
Day06 Assignment

### ISSUE THREAD

**Issue by AdiBarelMeisel** [szabgab/wis-python-course-2024-04#165]
Hi,

Please see the link to the Day06 Assignment. I apologize for the late submission.
https://github.com/AdiBarelMeisel/Assignments/tree/main/Day06

@szabgab 

Adi

**Comment by szabgab** [comment]
When talking about a programname or code snippet use backticks `single_cell_analysis.py`  instead of single quotes: 'single_cell_analysis.py'   (backticks are on the same key where ~ is)

In the test file there is no need to call the test functions, they will be called by `pytest` . In your case there is also no need to import `pytest`.

**Comment by AdiBarelMeisel** [comment]
Hey,
Corrected the issues that you mention. 
Thank you for noticing these issues.
Adi

@szabgab

**Comment by szabgab** [comment]
much better
