### ISSUE TITLE
Shahar- Assignment 2

### ISSUE THREAD

**Issue by ShaharGarin** [szabgab/wis-python-course-2024-04#50]
I've completed the second assignment. Here's a link to the repository where I'll put my solutions.
https://github.com/ShaharGarin/shahar_assignment.github.io

**Comment by szabgab** [comment]
The repo does not need to end with `.github.io` that is only needed for the web site. Please rename it via the 'Settings'

About the solution: 
* It is nice that you are checking if the input `isnumeric` before trying to call `int`, but

```python
`if user_num.isnumeric() == False:`
```
is better written as

```python
`if not user_num.isnumeric():`
```

It is also nice that you check if the number is in range, but then it would be better to  have "constants" for the borders of the range. Right now both the number 1 and number 20 is repeated 3 times.
You could have at the beginning of the code 

MIN = 1
MAX = 20

and then use these "variable" in the 3 relevant locations.

* It would be more readable to use an f-string instead of the last print statement with the commas: `print("Well done! The number is ", ran_num, ". You guessed right! It took you ", guess_count,  " attempts")`

* The `guess_count += 1` should only appear one - remember DRY
* There is no need for the `(( ))` around the `input` call.

**Comment by ShaharGarin** [comment]
Thanks for the feedback. 
Implemented the changes you suggested in the assignment (and made a couple other small updates in the text) and changed the repository name.

**Comment by szabgab** [comment]
nice.
* In this case MIN and MAX should be all upper-case, that's what indicated to the reader that these "variables"  should never change
* You should use these also in the  `input` call so if and when you decided to play in a different range you only need to update the code in one place.
